# Generated by Django 5.2.6 on 2025-09-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('cin', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('numéro', models.IntegerField()),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(db_column='prénom', max_length=50)),
                ('classe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eleves',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.IntegerField(primary_key=True, serialize=False)),
                ('id_classe', models.CharField(max_length=50)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('matricule_eleve', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('cin', models.OneToOneField(db_column='cin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.employer')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('cin', models.OneToOneField(db_column='cin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.employer')),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.IntegerField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=50)),
                ('id_eleve', models.ForeignKey(db_column='id_eleve', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.eleve')),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('id_matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.matiere')),
                ('coefficient', models.IntegerField()),
                ('appresiation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('id_classe', models.ForeignKey(db_column='id_classe', on_delete=django.db.models.deletion.CASCADE, to='school.classe')),
                ('id_eleve', models.ForeignKey(db_column='id_eleve', on_delete=django.db.models.deletion.CASCADE, to='school.eleve')),
                ('id_note', models.ForeignKey(db_column='id_note', on_delete=django.db.models.deletion.CASCADE, to='school.note')),
            ],
            options={
                'db_table': 'noter',
                'unique_together': {('id_matiere', 'id_eleve', 'id_note', 'id_classe')},
            },
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('cin', models.ForeignKey(db_column='cin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.enseignant')),
                ('id_classe', models.ForeignKey(db_column='id_classe', on_delete=django.db.models.deletion.CASCADE, to='school.classe')),
                ('id_matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='school.matiere')),
            ],
            options={
                'db_table': 'enseigner',
                'unique_together': {('cin', 'id_matiere', 'id_classe')},
            },
        ),
    ]
