# Generated by Django 5.2.6 on 2025-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_employer_user_enseigner_id_noter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='prenom',
            new_name='prénom',
        ),
        migrations.AlterField(
            model_name='employer',
            name='numéro',
            field=models.IntegerField(db_column='numéro'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='prénom',
            field=models.CharField(blank=True, db_column='prénom', max_length=50, null=True),
        ),
    ]
